language: node_js
node_js:
  - '6.9.1'
cache:
  directories:
    - ~/.nvm
    - node_modules
services:
  - docker
git:
  depth: 1
env:
  global:
    - RELEASE_BRANCH="master"
    - DOCKER_HUB_ACCOUNT=nebo15
    - MAIN_BRANCHES="master develop"
before_install:
  - chmod -R +x bin
install:
  - npm install
  - bower install
script:
  - touch .env
  - ./bin/version-increment.sh && ./bin/build.sh && ./bin/start.sh || { exit 1; }
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
    if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then
      echo "[E] Container is not started\!";
      docker logs gandalf.landing.web --details --since 5h;
      exit 1;
    fi;
after_success:
  - ./bin/ci/push.sh
after_script:
  - npm run docker:down
